### ISSUE TITLE
Add Dominica holidays

### ISSUE THREAD

**Issue by arkid15r** [vacanza/python-holidays#1172]
Useful links:
  - https://en.wikipedia.org/wiki/Public_holidays_in_Dominica
  - https://www.timeanddate.com/holidays/dominica/
  - http://dominica.gov.dm/about-dominica/public-holidays

**Comment by arkid15r** [comment]
> I'll take this up after Haiti
> 
> Public Holidays act itself: https://www.dominica.gov.dm/laws/chapters/chap19-10.pdf Observance rule: https://pressroomopm.gov.dm/notice-public-holiday-order-2022/

Thanks @PPsyrius!

**Comment by PPsyrius** [comment]
@arkid15r @KJhellico Quick question

According to Dominica's `Public Holidays Act`, `Labour Day` is supposed to be on `May, 1st`
- https://www.dominica.gov.dm/laws/chapters/chap19-10.pdf

However, this has been __*de facto*__ held on the `1st Monday of May` since at least 2011 to the present day (2024), according to their government sources:
- https://dominicaconsulategreece.com/dominica/public-holidays/
- http://www.q95da.com/news/q95-news-received-on-december-29-2020-at-731pm-the-official-public-holiday-calendar-for-2021-approved-by-the-government-of-dominica
- https://dominica.gov.dm/about-dominica/public-holidays

I don't think I can find the exact amendments to this particular law either, so I'm out of ideas here about how to implement this...

**Comment by arkid15r** [comment]
@PPsyrius maybe implement it just like you've described: use May 1st as a default and the actual dates for 2010-2024.

@KJhellico any ideas?
