### ISSUE TITLE
Add Vanuatu holidays

### ISSUE THREAD

**Issue by arkid15r** [vacanza/python-holidays#1298]
Links:
  - https://en.wikipedia.org/wiki/Public_holidays_in_Vanuatu
  - https://www.timeanddate.com/holidays/vanuatu/
  - https://www.gov.vu/index.php/events/holidays

**Comment by Strategos1** [comment]
Issue with make check and make pre-commit

Hi. 
I want to contribute to the module because it helped me, so I want to return the favour and contribute with Adding Vanuatu.

I made two files vanuatu.py, test_vanuatu.py. I modified registry.py, __init__.py and README.srt

I created a new environment and started with `$ make setup` I ran into a problem with makefile errors

![Screenshot 2023-08-09 125407](https://github.com/vacanza/python-holidays/assets/109518520/150da041-e729-4d68-9681-0793ab25739c)

I tried to `$ make check`. The same error

It passed `$ make test`, even `$ pytest -s tests/countries/test_vanuatu.py`

And on `$ make pre-commit`, it failed rstcheck

![Screenshot 2023-08-09 130127](https://github.com/vacanza/python-holidays/assets/109518520/fd0e9827-7890-4f38-88d0-4eb907c6d27b)

Could someone please help me?

**Comment by arkid15r** [comment]
Hi @Strategos1 
thank you for making Vanuatu holidays support possible!

I guess it would be easier to help you if you exported your code (I understand it's WIP). Try git commit / git push with --no-verify flag.

For the next troubleshooting step I'd run `scripts/l10n/generate_po_files.py`

**Comment by KJhellico** [comment]
@Strategos1,
Seems it's `babel` problem. As advised [here](https://github.com/nektos/act/issues/1853#issuecomment-1620853901), try to run:
```bash
TZ=UTC make setup
```
I just tried this on gitpod.io and there are no errors. Same for other `make` commands.

**Comment by arkid15r** [comment]
Accepted and merged, thank you!

**Comment by Strategos1** [comment]
No I thank you for all your help :)
