### ISSUE TITLE
2 Missing UK Bank holidays

### ISSUE THREAD

**Issue by will-judge** [vacanza/python-holidays#1449]
There are normally 8 bank holidays in the UK each year (https://www.gov.uk/bank-holidays), whilst holidays.CountryHoliday("UnitedKingdom", years=2023) lists 6 regulars bank holidays. 

The missing bank holidays are the "Summer bank holiday" and the "Easter Monday bank holiday". This error occurs in both 2023 and 2024.

**Comment by KJhellico** [comment]
@will-judge, thank you for your comments and useful source! 
These holidays (Easter Monday and Late Summer Bank Holiday) are not common to the entire United Kingdom, but only to England, Wales and Northern Ireland (they are not holidays in Scotland). So you may find them in something like
`holidays.CountryHoliday("UK", subdiv="ENG", years=2023)`
(also "NIR" or "WLS" instead of "ENG").

**Comment by arkid15r** [comment]
I believe this can be closed.
