### ISSUE TITLE
Weekend days in different countries 

### ISSUE THREAD

**Issue by ncooder** [vacanza/python-holidays#1917]
Bangladesh's weekend days are Friday and Saturday, and for other countries listed here, the weekend days can be different:
[Wikipedia](https://en.m.wikipedia.org/wiki/Workweek_and_weekend).

**Comment by PPsyrius** [comment]
I did some quick checks and they're already accounted for [Malaysia](https://github.com/vacanza/python-holidays/blob/ae24041f7ffaa6ccc0e28ba054560fc2e16dcc19/holidays/countries/malaysia.py)'s and [Saudi Arabia](https://github.com/vacanza/python-holidays/blob/ae24041f7ffaa6ccc0e28ba054560fc2e16dcc19/holidays/countries/saudi_arabia.py)'s implementation.

While this likely won't affect Bangladesh in practice (since the current implementation has no in-lieu observances), adding them would be good as you said.
